# Generated by Django 3.2.4 on 2021-08-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('P', 'Python'), ('J', 'JavaScript'), ('K', 'Kotlin'), ('U', 'UX Research'), ('UI', 'UI/UX Design'), ('P', 'Professional Development'), ('N', 'Navigating Your Journey')], max_length=20)),
                ('course_code', models.CharField(choices=[('P', 'P-BackEnd'), ('J', 'J-FrontEnd'), ('K', 'K-MobFront'), ('U', 'U-Rsh'), ('UI', 'UI/UX'), ('p', 'PD'), ('N', 'NYJ')], max_length=10)),
                ('trainer', models.CharField(max_length=10)),
                ('course_description', models.TextField()),
                ('syllabus', models.FileField(upload_to='files/')),
            ],
        ),
    ]
