# Generated by Django 3.2.4 on 2021-09-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(choices=[('P', 'P-BackEnd'), ('J', 'J-FrontEnd'), ('K', 'K-MobFront'), ('U', 'U-Rsh'), ('UI', 'UI/UX'), ('p', 'PD'), ('N', 'NYJ')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('P', 'Python'), ('J', 'JavaScript'), ('K', 'Kotlin'), ('U', 'UX Research'), ('UI', 'UI/UX Design'), ('P', 'Professional Development'), ('N', 'Navigating Your Journey')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='trainer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
