# Generated by Django 3.2.4 on 2021-08-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=10)),
                ('event_start', models.TimeField()),
                ('event_end', models.TimeField()),
                ('attendees', models.EmailField(max_length=254)),
                ('event_link', models.URLField()),
            ],
        ),
    ]
