<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-09-20 06:00
=======
# Generated by Django 3.2.4 on 2021-09-18 18:51
>>>>>>> 8292ec9566cf33c4b5774c31a09f6f38eef4d6cf

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Others')], max_length=10)),
                ('age', models.PositiveSmallIntegerField(default=None)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('classes_name', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('nationality', models.CharField(choices=[('K', 'Kenyan'), ('U', 'Ugandan'), ('R', 'Rwandan'), ('S', 'Sudan'), ('S', 'South Sudan')], default=None, max_length=10, null=True)),
                ('national_id', models.CharField(default=None, max_length=20, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('phone_number', models.CharField(default=None, max_length=14, null=True)),
                ('medical_record', models.FileField(default=None, null=True, upload_to='files/')),
                ('city', models.CharField(default=None, max_length=15, null=True)),
                ('academic_year', models.IntegerField(default=None, null=True)),
                ('guardian_name', models.CharField(default=None, max_length=20, null=True)),
                ('guardian_contact', models.CharField(default=None, max_length=14, null=True)),
                ('admission_date', models.DateField(default=None, null=True)),
                ('room_no', models.SmallIntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
