# Generated by Django 3.2.4 on 2021-09-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_year',
        ),
    ]
