# Generated by Django 3.2.4 on 2021-07-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='classes_name',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_contact',
            field=models.CharField(default=None, max_length=14),
        ),
        migrations.AddField(
            model_name='student',
            name='home_location',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_record',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='national_id',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=None, max_length=14),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
    ]
