# Generated by Django 3.2.4 on 2021-07-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210723_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='home_location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='room_no',
            field=models.SmallIntegerField(default=None),
        ),
    ]
