# Generated by Django 3.2.4 on 2021-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_record',
            field=models.FileField(default=None, upload_to='files/'),
        ),
    ]
