# Generated by Django 3.2.4 on 2021-08-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210730_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.BigIntegerField(default=None),
        ),
    ]
