# Generated by Django 3.2.4 on 2021-08-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='laptop_serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes_name',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_no',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
