# Generated by Django 3.2.4 on 2021-09-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210910_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
