# Generated by Django 3.2.4 on 2021-09-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_student_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
