# Generated by Django 3.2.4 on 2021-09-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
